local install = require("luarocks.install")
local test_enviroment = require( "new_test/test_enviroment")

describe( 'LuaRocks install #install_whitebox', function()
	describe( 'basic test #install_whitebox_new', function()
		it('trivial_test2', function()
			assert.are.same(1,1)
		end)
	end)

	describe( 'basic test #install_whitebox_old', function()
		it('trivial_test2', function()
			assert.are.same(1,1)
		end)
	end)
end)

--TODO
describe( 'Luarocks black-box tests #install_blackbox', function()
	local test_utils = test_enviroment.main()
	it('luarocks install with no arguments', function()
		test_enviroment.reset_environment(test_utils.testing_paths, test_utils.md5sums)
		local output = test_utils.luarocks(" install", test_utils.testing_env_variables)
		assert.are.same(1,1)
	end)
	it('luarocks install with invalid argument', function()
		test_enviroment.reset_environment(test_utils.testing_paths, test_utils.md5sums)
		local output = test_utils.luarocks(" install invalid", test_utils.testing_env_variables)
		assert.are.same(1,1)
	end)
	 it('luarocks install luasec with skipping dependency checks', function()
		test_enviroment.reset_environment(test_utils.testing_paths, test_utils.md5sums)
		local output = test_utils.luarocks(" install luasec --nodeps;", test_utils.testing_env_variables)
		assert.are.same(1,1)
	end)
end)